### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by Jogai** [nwgat/chocolatey-packages#1]
Hi,

I saw that several of your packages are outdated:

- openshot
- LFTP
- HardWipe
- DVDFab Passkey (see also: https://gist.github.com/choco-bot/5da52b07d78d726f660881e024301e8c)
- tinc (stable version)

**Comment by nwgat** [comment]
openshot has been updated to 2.2 on chocolately.com
lftp is compiled by me and it fails to compile on 4.7.0 branch
passkey = need to figure that out
tinc = pre is probably what you want, stable is not

also this repo isnt always updated ;)

**Comment by Jogai** [comment]
Cool, thanks!

**Comment by nwgat** [comment]
got lftp working again https://nwgat.ninja/lftp-4-7-5-for-windows/

**Comment by Jogai** [comment]
Openshot has released 2.3.1 today  😄
